//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CG.Blazor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CG.Blazor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It appears the plugin assembly &apos;{0}&apos; can&apos;t be found. See inner exception for more detail..
        /// </summary>
        internal static string ApplicationBuilderExtensions_AsmName {
            get {
                return ResourceManager.GetString("ApplicationBuilderExtensions_AsmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It appears the script tag &apos;{0}&apos; is missing the &apos;_content/&apos; portion of the tag..
        /// </summary>
        internal static string ApplicationBuilderExtensions_MissingContent {
            get {
                return ResourceManager.GetString("ApplicationBuilderExtensions_MissingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It appears the script tag &apos;{0}&apos; is missing a &apos;/&apos; after the assembly name..
        /// </summary>
        internal static string ApplicationBuilderExtensions_MissingSlash {
            get {
                return ResourceManager.GetString("ApplicationBuilderExtensions_MissingSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It appears the plugin assembly &apos;{0}&apos; doesn&apos;t have a wwwroot folder, or doesn&apos;t have any embedded resources in that folder, or doesn&apos;t have an embedded manifest. See inner exception for more detail..
        /// </summary>
        internal static string ApplicationBuilderExtensions_WwwRoot {
            get {
                return ResourceManager.GetString("ApplicationBuilderExtensions_WwwRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It appears the module: &apos;{0}&apos; either doesn&apos;t exist in assembly &apos;{1}&apos;. See inner exceptions for more detail..
        /// </summary>
        internal static string ServiceCollectionExtensions_EntryPoint {
            get {
                return ResourceManager.GetString("ServiceCollectionExtensions_EntryPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It appears the script path &apos;{0}&apos; contains HTML. HTML is not allowed in the path..
        /// </summary>
        internal static string ServiceCollectionExtensions_HtmlScript {
            get {
                return ResourceManager.GetString("ServiceCollectionExtensions_HtmlScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It appears the style sheet link &apos;{0}&apos; contains HTML. HTML is not allowed in the link..
        /// </summary>
        internal static string ServiceCollectionExtensions_HtmlStyle {
            get {
                return ResourceManager.GetString("ServiceCollectionExtensions_HtmlStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It appears the script &apos;{0}&apos; is not an embedded resource in assembly &apos;{1}&apos;!.
        /// </summary>
        internal static string ServiceCollectionExtensions_ResScript {
            get {
                return ResourceManager.GetString("ServiceCollectionExtensions_ResScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It appears the style sheet link &apos;{0}&apos; is not an embedded resource in assembly &apos;{1}&apos;!.
        /// </summary>
        internal static string ServiceCollectionExtensions_ResStyle {
            get {
                return ResourceManager.GetString("ServiceCollectionExtensions_ResStyle", resourceCulture);
            }
        }
    }
}
